export { default as AboutProducts } from "./About Products/AboutProducts";
export { default as Brand } from "./Brand/Brand";
export { default as CTA } from "./CTA/CTA";
export { default as Footer } from "./Footer/Footer";
export { default as Header } from "./Header/Header";
export { default as Navbar } from "./Navbar/Navbar";
export { default as NewProducts } from "./New Products/NewProducts";
export { default as NewShop } from "./New Shop/NewShop";
export { default as Offers } from "./Offers/Offers";
export { default as Products } from "./Products/Products";
